$ErrorActionPreference = "Stop"

$Main       = ".\switch\source\main.cpp"
$LiveHeader = ".\switch\include\live_search.hpp"
$LiveSource = ".\switch\source\live_search.cpp"
$CacheHdr   = ".\switch\include\scrape_cache.hpp"
$CacheSrc   = ".\switch\source\scrape_cache.cpp"
$JackettHdr = ".\switch\include\jackett_provider.hpp"
$Makefile   = ".\switch\Makefile"

foreach ($required in @($Main, $LiveHeader, $LiveSource, $Makefile)) {
    if (-not (Test-Path -LiteralPath $required)) {
        throw "Missing $required. Run this from the SwitchGamesBrowser repository root after the live-search/provider patches."
    }
}

$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)

    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }

    [System.IO.File]::WriteAllText(
        (Join-Path $PWD $Path),
        $Content,
        $Utf8NoBom
    )
}

function Backup-Once {
    param([string]$Path)
    $backup = "$Path.before-jackett-cache.bak"
    if (-not (Test-Path -LiteralPath $backup)) {
        Copy-Item -LiteralPath $Path -Destination $backup
    }
}

foreach ($path in @($Main, $LiveHeader, $LiveSource, $Makefile)) {
    Backup-Once $path
}

# ============================================================
# 1. Shared Jackett/Torznab helper.
#    Individual visible provider .cpp files are generated by
#    Update-Jackett-Providers.ps1.
# ============================================================

$jackettHeader = @'
#pragma once

#include "provider.hpp"
#include "provider_api_utils.hpp"

#include <fstream>
#include <regex>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

namespace sgb_jackett {

struct Config {
    std::string url;
    std::string apiKey;
};

inline Config loadConfig()
{
    constexpr const char* path =
        "sdmc:/switch/SwitchGamesBrowser/jackett.json";

    std::ifstream file(path, std::ios::binary);

    if (!file) {
        throw std::runtime_error(
            "Missing SD:/switch/SwitchGamesBrowser/jackett.json");
    }

    nlohmann::json root;
    file >> root;

    Config config;
    config.url =
        sgb_api::trim(
            root.value("url", std::string{}));
    config.apiKey =
        sgb_api::trim(
            root.value("apiKey", std::string{}));

    while (!config.url.empty() && config.url.back() == '/')
        config.url.pop_back();

    if (config.url.empty())
        throw std::runtime_error("Jackett URL is empty");

    if (config.apiKey.empty())
        throw std::runtime_error("Jackett API key is empty");

    if (
        config.url.rfind("http://", 0) != 0 &&
        config.url.rfind("https://", 0) != 0
    ) {
        throw std::runtime_error(
            "Jackett URL must start with http:// or https://");
    }

    return config;
}

inline std::vector<sgb::ProviderResult> search(
    const std::string& indexerId,
    const std::string& query)
{
    std::vector<sgb::ProviderResult> results;

    const std::string clean = sgb_api::trim(query);

    if (clean.empty())
        return results;

    const Config config = loadConfig();

    const std::string url =
        config.url +
        "/api/v2.0/indexers/" +
        sgb_api::urlEncode(indexerId) +
        "/results/torznab/api?apikey=" +
        sgb_api::urlEncode(config.apiKey) +
        "&t=search&q=" +
        sgb_api::urlEncode(clean);

    const std::string xml =
        sgb_api::httpGet(
            url,
            "application/rss+xml, application/xml, text/xml, */*");

    static const std::regex itemRe(
        R"(<item\b[\s\S]*?</item>)",
        std::regex::icase);

    std::unordered_set<std::string> seen;

    for (
        auto it =
            std::sregex_iterator(
                xml.begin(),
                xml.end(),
                itemRe);
        it != std::sregex_iterator();
        ++it
    ) {
        const std::string item = it->str();

        const std::string title =
            sgb_api::trim(
                sgb_api::tagValue(item, "title"));

        std::string magnet =
            sgb_api::trim(
                sgb_api::torznabAttr(
                    item,
                    "magneturl"));

        if (magnet.empty()) {
            magnet =
                sgb_api::trim(
                    sgb_api::torznabAttr(
                        item,
                        "magnet"));
        }

        if (magnet.empty()) {
            const std::string link =
                sgb_api::trim(
                    sgb_api::tagValue(
                        item,
                        "link"));

            if (link.rfind("magnet:", 0) == 0)
                magnet = link;
        }

        if (magnet.empty()) {
            const std::string guid =
                sgb_api::trim(
                    sgb_api::tagValue(
                        item,
                        "guid"));

            if (guid.rfind("magnet:", 0) == 0)
                magnet = guid;
        }

        std::string hash =
            sgb_api::lowerAscii(
                sgb_api::trim(
                    sgb_api::torznabAttr(
                        item,
                        "infohash")));

        if (hash.empty() && !magnet.empty())
            hash = sgb_api::hashFromMagnet(magnet);

        if (
            title.empty() ||
            !sgb_api::validInfoHash(hash)
        ) {
            continue;
        }

        if (!seen.insert(hash).second)
            continue;

        if (magnet.empty()) {
            magnet =
                sgb_api::magnetFromHash(
                    hash,
                    title);
        }

        sgb::ProviderResult row;
        row.title = title;
        row.magnet = magnet;
        row.infoHash = hash;
        results.push_back(std::move(row));
    }

    return results;
}

} // namespace sgb_jackett
'@

Write-Utf8NoBom $JackettHdr $jackettHeader

# Ensure switch/source/providers is built.
$makeText = [System.IO.File]::ReadAllText((Join-Path $PWD $Makefile))

if ($makeText -notmatch '(?m)^\s*SOURCES\s*:=.*source/providers') {
    $updated = [regex]::Replace(
        $makeText,
        '(?m)^(\s*SOURCES\s*:=\s*)source\s*$',
        '${1}source source/providers',
        1
    )

    if ($updated -eq $makeText) {
        throw "Could not add source/providers to switch/Makefile SOURCES."
    }

    Write-Utf8NoBom $Makefile $updated
}

# ============================================================
# 2. Persistent scrape cache.
#
# We cache:
#   - the final validated torrent/release list per game
#   - scrape timestamp
#   - debrid service used
#
# The existing app already persists DebridTorrentStatus via
# saveDebridStatuses(). Therefore Cached Scrape does NOT call
# TorBox/AllDebrid again: it reloads the final Release rows and
# reuses the persisted availability/file map.
# ============================================================

$cacheHeader = @'
#pragma once

#include "catalog.hpp"
#include "debrid.hpp"

#include <ctime>
#include <map>
#include <string>
#include <vector>

namespace sgb {

struct ScrapeCacheInfo {
    bool available = false;
    std::time_t savedAt = 0;
    size_t releaseCount = 0;
};

bool saveScrapeCache(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService,
    const std::vector<Release>& releases,
    const std::map<std::string, DebridTorrentStatus>& statuses);

bool loadScrapeCache(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService,
    std::vector<Release>& releases,
    std::map<std::string, DebridTorrentStatus>& statuses,
    std::time_t* savedAt = nullptr);

ScrapeCacheInfo scrapeCacheInfo(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService);

std::string scrapeCacheAgeText(std::time_t savedAt);

} // namespace sgb
'@

$cacheSource = @'
#include "scrape_cache.hpp"

#include <nlohmann/json.hpp>

#include <cerrno>
#include <cstdio>
#include <cstdint>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <sys/stat.h>
#include <vector>

namespace sgb {
namespace {

using Json = nlohmann::json;

uint64_t fnv1a64(const std::string& value)
{
    uint64_t hash = UINT64_C(1469598103934665603);

    for (unsigned char c : value) {
        hash ^= static_cast<uint64_t>(c);
        hash *= UINT64_C(1099511628211);
    }

    return hash;
}

std::string cacheKey(const std::string& title)
{
    std::ostringstream out;
    out << std::hex
        << std::setfill('0')
        << std::setw(16)
        << fnv1a64(title);

    return out.str();
}

bool ensureDir(const std::string& path)
{
    if (::mkdir(path.c_str(), 0777) == 0)
        return true;

    return errno == EEXIST;
}

std::string serviceFolder(DebridService service)
{
    switch (service) {
        case DebridService::TorBox:
            return "torbox";
        case DebridService::AllDebrid:
            return "alldebrid";
        default:
            return "none";
    }
}

std::string serviceDirectory(
    const std::string& root,
    DebridService service)
{
    return root + "cache/" + serviceFolder(service);
}

std::string cacheDirectory(
    const std::string& root,
    DebridService service)
{
    return serviceDirectory(root, service) + "/scrapes";
}

std::string cachePath(
    const std::string& root,
    const std::string& title,
    DebridService service)
{
    return cacheDirectory(root, service) +
        "/" +
        cacheKey(title) +
        ".json";
}

bool prepareCacheDirectory(
    const std::string& root,
    DebridService service)
{
    if (!ensureDir(root + "cache"))
        return false;

    if (!ensureDir(serviceDirectory(root, service)))
        return false;

    return ensureDir(cacheDirectory(root, service));
}

Json releaseToJson(const Release& release)
{
    return Json{
        {"title", release.title},
        {"magnet", release.magnet},
        {"infoHash", release.infoHash},
        {"source", release.source}
    };
}

bool releaseFromJson(
    const Json& item,
    Release& release)
{
    if (!item.is_object())
        return false;

    release.title =
        item.value(
            "title",
            std::string{});

    release.magnet =
        item.value(
            "magnet",
            std::string{});

    release.infoHash =
        item.value(
            "infoHash",
            std::string{});

    release.source =
        item.value(
            "source",
            std::string{});

    return
        !release.title.empty() &&
        (
            !release.infoHash.empty() ||
            !release.magnet.empty()
        );
}

bool readCache(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService,
    Json& json)
{
    std::ifstream file(
        cachePath(
            root,
            gameTitle,
            debridService),
        std::ios::binary);

    if (!file)
        return false;

    json =
        Json::parse(
            file,
            nullptr,
            false);

    if (
        json.is_discarded() ||
        !json.is_object()
    ) {
        return false;
    }

    if (json.value("version", 0) != 2)
        return false;

    if (
        json.value(
            "gameTitle",
            std::string{}) !=
        gameTitle
    ) {
        return false;
    }

    if (
        json.value(
            "debridService",
            std::string{}) !=
        serviceFolder(debridService)
    ) {
        return false;
    }

    return
        json.contains("releases") &&
        json["releases"].is_array() &&
        json.contains("statuses") &&
        json["statuses"].is_object();
}

} // namespace

bool saveScrapeCache(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService,
    const std::vector<Release>& releases,
    const std::map<std::string, DebridTorrentStatus>& statuses)
{
    if (!prepareCacheDirectory(root, debridService))
        return false;

    Json rows = Json::array();

    for (const auto& release : releases)
        rows.push_back(releaseToJson(release));

    Json statusJson =
        Json::parse(
            serializeDebridStatusJson(statuses),
            nullptr,
            false);

    if (
        statusJson.is_discarded() ||
        !statusJson.is_object()
    ) {
        statusJson = Json::object();
    }

    Json rootJson{
        {"version", 2},
        {"gameTitle", gameTitle},
        {"debridService", serviceFolder(debridService)},
        {
            "savedAt",
            static_cast<long long>(
                std::time(nullptr))
        },
        {"releases", std::move(rows)},
        {"statuses", std::move(statusJson)}
    };

    const std::string target =
        cachePath(
            root,
            gameTitle,
            debridService);

    const std::string temporary =
        target + ".tmp";

    {
        std::ofstream file(
            temporary,
            std::ios::binary |
            std::ios::trunc);

        if (!file)
            return false;

        const std::string payload =
            rootJson.dump();

        file.write(
            payload.data(),
            static_cast<std::streamsize>(
                payload.size()));

        file.flush();

        if (!file)
            return false;
    }

    std::remove(target.c_str());

    if (
        std::rename(
            temporary.c_str(),
            target.c_str()) != 0
    ) {
        std::remove(
            temporary.c_str());

        return false;
    }

    return true;
}

bool loadScrapeCache(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService,
    std::vector<Release>& releases,
    std::map<std::string, DebridTorrentStatus>& statuses,
    std::time_t* savedAt)
{
    Json json;

    if (
        !readCache(
            root,
            gameTitle,
            debridService,
            json)
    ) {
        return false;
    }

    std::vector<Release> loaded;

    for (const auto& item : json["releases"]) {
        Release release;

        if (releaseFromJson(item, release))
            loaded.push_back(
                std::move(release));
    }

    statuses =
        parseDebridStatusJson(
            json["statuses"].dump());

    if (savedAt) {
        *savedAt =
            static_cast<std::time_t>(
                json.value(
                    "savedAt",
                    0LL));
    }

    releases =
        std::move(loaded);

    return true;
}

ScrapeCacheInfo scrapeCacheInfo(
    const std::string& root,
    const std::string& gameTitle,
    DebridService debridService)
{
    ScrapeCacheInfo info;

    Json json;

    if (
        !readCache(
            root,
            gameTitle,
            debridService,
            json)
    ) {
        return info;
    }

    info.available = true;

    info.savedAt =
        static_cast<std::time_t>(
            json.value(
                "savedAt",
                0LL));

    info.releaseCount =
        json["releases"].size();

    return info;
}

std::string scrapeCacheAgeText(
    std::time_t savedAt)
{
    if (savedAt <= 0)
        return "unknown age";

    const std::time_t now =
        std::time(nullptr);

    if (now <= savedAt)
        return "just now";

    const long long seconds =
        static_cast<long long>(
            now - savedAt);

    if (seconds < 60)
        return "just now";

    const long long minutes =
        seconds / 60;

    if (minutes < 60)
        return
            std::to_string(minutes) +
            "m ago";

    const long long hours =
        minutes / 60;

    if (hours < 48)
        return
            std::to_string(hours) +
            "h ago";

    const long long days =
        hours / 24;

    return
        std::to_string(days) +
        "d ago";
}

} // namespace sgb
'@

Write-Utf8NoBom $CacheHdr $cacheHeader
Write-Utf8NoBom $CacheSrc $cacheSource

# ============================================================
# 3. Mark LiveSearchResult success/failure so a failed New
#    Scrape never destroys the user's previous good cache.
# ============================================================

$liveHpp =
    [System.IO.File]::ReadAllText(
        (Join-Path $PWD $LiveHeader))

if ($liveHpp -notmatch '\bbool\s+success\s*=') {
    $needle = @'
struct LiveSearchResult {
    std::vector<Release> releases;
    std::map<std::string, DebridTorrentStatus> statuses;
    std::string message;
};
'@

    $replacement = @'
struct LiveSearchResult {
    std::vector<Release> releases;
    std::map<std::string, DebridTorrentStatus> statuses;
    std::string message;
    bool success = false;
};
'@

    if (-not $liveHpp.Contains($needle)) {
        throw "Could not patch LiveSearchResult in live_search.hpp."
    }

    $liveHpp =
        $liveHpp.Replace(
            $needle,
            $replacement)
}

Write-Utf8NoBom $LiveHeader $liveHpp

$liveCpp =
    [System.IO.File]::ReadAllText(
        (Join-Path $PWD $LiveSource))

# Normalize source line endings so patch matching works regardless of
# whether Git/PowerShell wrote CRLF or LF.
$liveCpp = $liveCpp.Replace("`r`n", "`n")

# Empty-but-successful scrape.
$emptyNeedle = @'
        if (candidates.empty()) {
            output.message = "Search complete: no candidates found";
            progress.setText("Complete", "");
            progress.running.store(false);
            return output;
        }
'@

$emptyReplacement = @'
        if (candidates.empty()) {
            output.message = "Search complete: no candidates found";
            output.success = true;
            progress.setText("Complete", "");
            progress.running.store(false);
            return output;
        }
'@

if (
    $liveCpp.Contains($emptyNeedle) -and
    $liveCpp -notmatch
        'Search complete: no candidates found";\s*output\.success'
) {
    $liveCpp =
        $liveCpp.Replace(
            $emptyNeedle,
            $emptyReplacement)
}

# Normal successful completion.
# Use a regex instead of exact multi-line text so CRLF/spacing changes do
# not break the patch.
$completePattern =
    '(?m)^(?<indent>[ \t]*)progress\.setText\s*\(\s*"Complete"\s*,\s*""\s*\)\s*;'

$completeMatches =
    [regex]::Matches(
        $liveCpp,
        $completePattern)

if ($completeMatches.Count -eq 0) {
    throw "Could not locate successful completion in live_search.cpp."
}

# The final Complete marker is the normal successful path. Check only the
# short region immediately before that marker so an earlier zero-candidate
# success does not make us incorrectly skip this one.
$match =
    $completeMatches[
        $completeMatches.Count - 1]

$contextStart =
    [Math]::Max(
        0,
        $match.Index - 180)

$context =
    $liveCpp.Substring(
        $contextStart,
        $match.Index - $contextStart)

if ($context -notmatch 'output\.success\s*=\s*true;') {
    $indent =
        $match.Groups['indent'].Value

    $liveCpp =
        $liveCpp.Substring(0, $match.Index) +
        $indent + "output.success = true;`n" +
        $liveCpp.Substring($match.Index)
}

Write-Utf8NoBom $LiveSource $liveCpp

# ============================================================
# 4. main.cpp: Cached Scrape / New Scrape selection page.
# ============================================================

$main =
    [System.IO.File]::ReadAllText(
        (Join-Path $PWD $Main))

# Same CRLF/LF normalization as live_search.cpp.
$main = $main.Replace("`r`n", "`n")

# Include cache helper.
if ($main -notmatch '#include\s+"scrape_cache\.hpp"') {
    if ($main -match '#include\s+"live_search\.hpp"') {
        $main =
            $main.Replace(
                '#include "live_search.hpp"',
                "#include `"live_search.hpp`"`r`n#include `"scrape_cache.hpp`"")
    }
    else {
        throw "main.cpp does not include live_search.hpp."
    }
}

# Add ScrapeChoice enum value.
if ($main -notmatch '\bScrapeChoice\b') {
    $enumPattern =
        'enum class Page \{([^}]*)\};'

    $enumMatch =
        [regex]::Match(
            $main,
            $enumPattern)

    if (-not $enumMatch.Success) {
        throw "Could not locate Page enum in main.cpp."
    }

    $inside =
        $enumMatch.Groups[1].Value.Trim()

    $replacement =
        "enum class Page { $inside, ScrapeChoice };"

    $main =
        [regex]::Replace(
            $main,
            $enumPattern,
            $replacement,
            1)
}

# Extend live-search state.
if ($main -notmatch 'scrapeChoiceGameIndex') {
    $needle = @'
    size_t liveSearchGameIndex = 0;
'@

    $replacement = @'
    size_t liveSearchGameIndex = 0;

    size_t scrapeChoiceGameIndex = 0;
    size_t scrapeChoiceCursor = 0;
    bool scrapeChoiceHasCache = false;
    std::time_t scrapeChoiceSavedAt = 0;
    size_t scrapeChoiceReleaseCount = 0;
'@

    if (-not $main.Contains($needle)) {
        throw "Could not locate liveSearchGameIndex state in main.cpp."
    }

    $main =
        $main.Replace(
            $needle,
            $replacement)
}

# Open-choice helper is placed immediately before startLiveSearch.
if ($main -notmatch 'auto openScrapeChoice') {
    $marker =
        '    auto startLiveSearch = [&](size_t gameIndex) {'

    if (-not $main.Contains($marker)) {
        throw "Could not locate startLiveSearch in main.cpp."
    }

    $insert = @'
    auto openScrapeChoice = [&](size_t gameIndex) {
        if (gameIndex >= games.size())
            return;

        scrapeChoiceGameIndex = gameIndex;
        scrapeChoiceCursor = 0;

        const auto cache =
            sgb::scrapeCacheInfo(
                root,
                games[gameIndex].title,
                debridConfig.service);

        scrapeChoiceHasCache =
            cache.available;

        scrapeChoiceSavedAt =
            cache.savedAt;

        scrapeChoiceReleaseCount =
            cache.releaseCount;

        page = Page::ScrapeChoice;
    };

'@

    $main =
        $main.Replace(
            $marker,
            $insert + $marker)
}

# Detail A should open the two-choice page, not start immediately.
$detailStartPattern =
    'if\s*\(keys\s*&\s*HidNpadButton_A\)\s*\{\s*startLiveSearch\(rows\[cursor\]\);\s*\}'

if (
    $main -match $detailStartPattern -and
    $main -notmatch
        'openScrapeChoice\(rows\[cursor\]\)'
) {
    $main =
        [regex]::Replace(
            $main,
            $detailStartPattern,
            "if (keys & HidNpadButton_A) {`n                    openScrapeChoice(rows[cursor]);`n                }",
            1)
}

# Fallback from old pre-live-search behavior.
if ($main -notmatch 'openScrapeChoice\(rows\[cursor\]\)') {
    $oldPattern =
        'if\s*\(keys\s*&\s*HidNpadButton_A\)\s*\{\s*if\s*\(g\.releases\.empty\(\)\).*?\}'

    $oldRegex =
        [regex]::new(
            $oldPattern,
            [System.Text.RegularExpressions.RegexOptions]::Singleline)

    $updated =
        $oldRegex.Replace(
            $main,
            "if (keys & HidNpadButton_A) {`n                    openScrapeChoice(rows[cursor]);`n                }",
            1)

    if ($updated -eq $main) {
        throw "Could not patch Detail A action to open ScrapeChoice."
    }

    $main = $updated
}

# Save a new cache only after a SUCCESSFUL New Scrape.
if ($main -notmatch 'saveScrapeCache\(') {
    $needle = @'
            auto result = pendingLiveSearch.get();

            if (liveSearchGameIndex < games.size()) {
                games[liveSearchGameIndex].releases =
                    std::move(result.releases);
'@

    $replacement = @'
            auto result = pendingLiveSearch.get();

            if (liveSearchGameIndex < games.size()) {
                const bool scrapeSucceeded =
                    result.success;

                const bool scrapeCached =
                    !scrapeSucceeded ||
                    sgb::saveScrapeCache(
                        root,
                        games[liveSearchGameIndex].title,
                        debridConfig.service,
                        result.releases,
                        result.statuses);

                games[liveSearchGameIndex].releases =
                    std::move(result.releases);
'@

    if (-not $main.Contains($needle)) {
        throw "Could not locate completed live-search block in main.cpp."
    }

    $main =
        $main.Replace(
            $needle,
            $replacement)

    $needle2 = @'
                saveDebridStatuses();
                torrentCursor = 0;
'@

    $replacement2 = @'
                saveDebridStatuses();
                torrentCursor = 0;
'@

    if (-not $main.Contains($needle2)) {
        throw "Could not locate saveDebridStatuses() in completed search block."
    }

    $main =
        $main.Replace(
            $needle2,
            $replacement2)

    # Preserve the search result message, but surface a cache-write failure.
    $cacheStatusReplacement =
        '$1' +
        "`n                if (scrapeSucceeded && !scrapeCached) status += `" (cache save failed)`";"

    $main =
        [regex]::Replace(
            $main,
            '(status\s*=\s*result\.message\s*;)',
            $cacheStatusReplacement,
            1)
}

# Add ScrapeChoice input before Browse input.
if ($main -notmatch 'page == Page::ScrapeChoice\) \{\s*if \(keys & HidNpadButton_B\)') {
    $marker =
        '        if (page == Page::Browse) {'

    if (-not $main.Contains($marker)) {
        throw "Could not locate Browse input block."
    }

    $input = @'
        if (page == Page::ScrapeChoice) {
            if (keys & HidNpadButton_B) {
                page = Page::Detail;
            }

            if (keys & HidNpadButton_AnyUp) {
                scrapeChoiceCursor =
                    scrapeChoiceCursor == 0
                        ? 1
                        : 0;
            }

            if (keys & HidNpadButton_AnyDown) {
                scrapeChoiceCursor =
                    scrapeChoiceCursor == 0
                        ? 1
                        : 0;
            }

            if (keys & HidNpadButton_A) {
                if (
                    scrapeChoiceGameIndex >=
                    games.size()
                ) {
                    status =
                        "Selected game is no longer available";
                    page = Page::Browse;
                }
                else if (scrapeChoiceCursor == 0) {
                    std::vector<sgb::Release> cached;
                    std::map<
                        std::string,
                        sgb::DebridTorrentStatus
                    > cachedStatuses;
                    std::time_t savedAt = 0;

                    if (
                        !sgb::loadScrapeCache(
                            root,
                            games[
                                scrapeChoiceGameIndex
                            ].title,
                            debridConfig.service,
                            cached,
                            cachedStatuses,
                            &savedAt)
                    ) {
                        status =
                            "No cached scrape available for this game";
                    }
                    else {
                        games[
                            scrapeChoiceGameIndex
                        ].releases =
                            std::move(cached);

                        for (auto& pair : cachedStatuses) {
                            debridStatuses[pair.first] =
                                std::move(pair.second);
                        }

                        torrentCursor = 0;
                        selectedFiles.clear();

                        status =
                            "Loaded cached scrape (" +
                            sgb::scrapeCacheAgeText(
                                savedAt) +
                            ")";

                        page = Page::Torrents;
                    }
                }
                else {
                    startLiveSearch(
                        scrapeChoiceGameIndex);
                }
            }

'@

    $main =
        $main.Replace(
            $marker,
            $input + "        } else if (page == Page::Browse) {")
}

# Render two-button page before SearchProgress/Providers/Settings.
if ($main -notmatch '"SCRAPE OPTIONS"') {
    $renderMarker =
        '        if (page == Page::SearchProgress) {'

    if (-not $main.Contains($renderMarker)) {
        $renderMarker =
            '        if (page == Page::Providers) {'
    }

    if (-not $main.Contains($renderMarker)) {
        $renderMarker =
            '        if (page == Page::Settings) {'
    }

    if (-not $main.Contains($renderMarker)) {
        throw "Could not locate a render-chain insertion point."
    }

    $render = @'
        if (page == Page::ScrapeChoice) {
            const std::string gameTitle =
                scrapeChoiceGameIndex < games.size()
                    ? games[scrapeChoiceGameIndex].title
                    : "";

            label(
                renderer,
                big,
                "SCRAPE OPTIONS",
                32,
                72,
                1200,
                green);

            label(
                renderer,
                big,
                gameTitle,
                32,
                118,
                1200,
                white);

            SDL_Rect cachedRow{
                32,
                205,
                1216,
                94
            };

            SDL_Rect newRow{
                32,
                320,
                1216,
                94
            };

            rect(
                renderer,
                cachedRow,
                scrapeChoiceCursor == 0
                    ? SDL_Color{28,28,28,255}
                    : SDL_Color{14,14,14,255});

            rect(
                renderer,
                newRow,
                scrapeChoiceCursor == 1
                    ? SDL_Color{28,28,28,255}
                    : SDL_Color{14,14,14,255});

            label(
                renderer,
                big,
                "Cached Scrape",
                54,
                222,
                1140,
                scrapeChoiceCursor == 0
                    ? green
                    : white);

            if (scrapeChoiceHasCache) {
                label(
                    renderer,
                    small,
                    std::to_string(
                        scrapeChoiceReleaseCount) +
                    " torrent(s)  |  " +
                    sgb::scrapeCacheAgeText(
                        scrapeChoiceSavedAt) +
                    "  |  availability cached",
                    54,
                    266,
                    1140,
                    muted);
            }
            else {
                label(
                    renderer,
                    small,
                    "No cache for the current debrid service",
                    54,
                    266,
                    1140,
                    muted);
            }

            label(
                renderer,
                big,
                "New Scrape",
                54,
                337,
                1140,
                scrapeChoiceCursor == 1
                    ? green
                    : white);

            label(
                renderer,
                small,
                "Search enabled providers and refresh cached availability",
                54,
                381,
                1140,
                muted);

            label(
                renderer,
                small,
                "A Select    B Back",
                32,
                650,
                1200,
                muted);

'@

    $main =
        $main.Replace(
            $renderMarker,
            $render +
            "        } else if (" +
            $renderMarker.Substring(
                "        if (".Length))
}

Write-Utf8NoBom $Main $main

Write-Host ""
Write-Host "Jackett + Cached/New Scrape patch v2 applied." -ForegroundColor Green
Write-Host ""
Write-Host "Added:"
Write-Host "  switch/include/jackett_provider.hpp"
Write-Host "  switch/include/scrape_cache.hpp"
Write-Host "  switch/source/scrape_cache.cpp"
Write-Host ""
Write-Host "Updated:"
Write-Host "  switch/include/live_search.hpp"
Write-Host "  switch/source/live_search.cpp"
Write-Host "  switch/source/main.cpp"
Write-Host "  switch/Makefile"
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  1. Run Update-Jackett-Providers.ps1"
Write-Host "  2. Copy jackett.json to the Switch SD"
Write-Host "  3. Build the NRO"
